import type { Metadata } from "next";
import "@/ui/css/globals.css";
import StyledJsxRegistry from "../components/registry";
import { GluestackUIProvider } from "@/ui/providers/gluestack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body className={"antialiased"} style={{ display: "flex" }}>
        <StyledJsxRegistry>
          <GluestackUIProvider mode="system">{children}</GluestackUIProvider>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
