[package]
name = "typerbeast-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3" }
axum-extra = { version = "0.10.1", features = ["typed-header"] }
dotenvy = "0.15.7"
log = "0.4.27"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }

[profile.release]
lto = "thin"
strip = true
opt-level = 3
# panic = "abort"
codegen-units = 1
